name: PAR
version: 0.90
abstract: Perl Archive Toolkit
license: perl
distribution_type: module
requires:
  perl: 5.6.0
  File::Temp: 0.05
  Compress::Zlib: 1.3
  Archive::Zip: 1
  Module::ScanDeps: 0.45
  PAR::Dist: 0.06
recommends:
  Digest: Module::Signature
procides:
  App::Packer::PAR:
    file: lib/App/Packer/PAR.pm
    version: 0.13
  PAR:
    file: lib/PAR.pm
    version: 0.90
  PAR::Filter:
    file: lib/PAR/Filter.pm
    version: 0.02
  PAR::Filter::Bleach:
    file: lib/PAR/Filter/Bleach.pm
  PAR::Filter::Bytecode:
    file: lib/PAR/Filter/Bytecode.pm
  PAR::Filter::Obfuscate:
    file: lib/PAR/Filter/Obfuscate.pm
  PAR::Filter::PatchContent:
    file: lib/PAR/Filter/PatchContent.pm
  PAR::Filter::PodStrip:
    file: lib/PAR/Filter/PodStrip.pm
  PAR::Heavy:
    file: lib/PAR/Heavy.pm
    version: 0.08
  PAR::Packer:
    file: lib/PAR/Packer.pm
    version: 0.12
no_index:
  directory:
    - contrib
    - inc
generated_by: Module::Install version 0.41
