abstract: Perl Archive Tookit
author: Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.62
license: perl
name: PAR
no_index: 
  directory: 
    - contrib
    - inc
    - t
provides: 
  App::Packer::PAR: 
    file: lib/App/Packer/PAR.pm
    version: 0.91
  PAR: 
    file: lib/PAR.pm
    version: 0.93
  PAR::Filter: 
    file: lib/PAR/Filter.pm
    version: 0.02
  PAR::Filter::Bleach: 
    file: lib/PAR/Filter/Bleach.pm
  PAR::Filter::Bytecode: 
    file: lib/PAR/Filter/Bytecode.pm
  PAR::Filter::Obfuscate: 
    file: lib/PAR/Filter/Obfuscate.pm
  PAR::Filter::PatchContent: 
    file: lib/PAR/Filter/PatchContent.pm
  PAR::Filter::PodStrip: 
    file: lib/PAR/Filter/PodStrip.pm
  PAR::Heavy: 
    file: lib/PAR/Heavy.pm
    version: 0.08
  PAR::Packer: 
    file: lib/PAR/Packer.pm
    version: 0.12
recommends: 
  Digest: Module::Signature
requires: 
  Archive::Zip: 1
  Compress::Zlib: 1.3
  File::Temp: 0.05
  Module::ScanDeps: 0.56
  PAR::Dist: 0.08
  perl: 5.6.0
version: 0.93
